version: "3.9"
services:
  web:
    build: ../apps/web
    command: pnpm start
    ports:
      - "3000:3000"
  api:
    build: ../apps/api
    command: pnpm start
    ports:
      - "3001:3001"
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
